# Generated by Django 2.1.5 on 2019-06-02 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Evento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentarioevento',
            name='evento',
        ),
        migrations.RemoveField(
            model_name='comentarioevento',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='ComentarioEvento',
        ),
    ]
