# Generated by Django 2.1.5 on 2019-06-06 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evento', '0002_auto_20190601_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fecha',
            field=models.DateField(),
        ),
    ]
