# Generated by Django 2.1.5 on 2019-05-22 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioExtravio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(max_length=160)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Extravio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anuncio', models.CharField(max_length=160)),
                ('recompensa', models.FloatField()),
                ('raza', models.CharField(max_length=60)),
                ('color', models.CharField(max_length=40)),
                ('fecha_extravio', models.DateField()),
                ('nombre', models.CharField(max_length=30)),
                ('tamano', models.CharField(max_length=20)),
                ('senas_particulares', models.TextField(max_length=360)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('descripcion', models.TextField(max_length=360)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='Extravio')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Usuario.Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='comentarioextravio',
            name='extravio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Extravio.Extravio'),
        ),
        migrations.AddField(
            model_name='comentarioextravio',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Usuario.Usuario'),
        ),
    ]
