# Generated by Django 2.1.5 on 2019-05-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Extravio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extravio',
            name='lat',
            field=models.DecimalField(decimal_places=16, max_digits=20),
        ),
        migrations.AlterField(
            model_name='extravio',
            name='lon',
            field=models.DecimalField(decimal_places=16, max_digits=20),
        ),
    ]
